language: python

sudo: false

python:
  - "3.10"
  - "3.11"
  - "3.12"

matrix:
  include:
    - python: "3.10"
      env: PY_VER_TOX=py310
    - python: "3.11"
      env: PY_VER_TOX=py311
    - python: "3.12"
      env: PY_VER_TOX=py312

install:
  - pip install -U tox coveralls

script:
  - tox -e "$PY_VER_TOX-django50",flake8

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
