[tox]
envlist =
    flake8
    isort
    py{310,311,312}-django50

skip_missing_interpreters = True

[testenv]
whitelist_externals =
    gulp
    sh
    sleep
commands =
    {envpython} --version
    - coverage erase
    coverage run test_settings.py
    - coverage report
deps =
    -r{toxinidir}/test_requirements.txt
    django50: django>=5.0,<5.1
    django50: django-cms>=4.1,<4.2

[testenv:flake8]
deps = flake8
commands = flake8

[testenv:isort]
deps = isort
commands = isort -c -rc -df aldryn_people
skip_install = true

[flake8]
exclude = aldryn_people/migrations/*,docs/conf.py,build/*
max-line-length = 120
